include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    # file_names: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_dynamic_calls: false
    flutter_style_todos: true
    # Generated items have issues
    cascade_invocations: false
    unnecessary_raw_strings: false
