version: "3.8"
services:
  pg:
    image: postgres:alpine
    restart: always
    ports:
      - 5454:5432
    volumes:
      - pg_data_test:/var/lib/postgresql/data
    env_file:
      - pg.env
    shm_size: 1g
    # resources:
    #   limits:
    #     cpus: 4
    #     memory: 4g
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
      # - rabbit_data/log/:/var/log/rabbitmq
volumes:
  pg_data_test:
  rabbit_data:
