name: bita_markets
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4
publish_to: none
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  d_orm:
    path: /home/nurad/d-orm
  dart_jsonwebtoken: 
  http: 
  http_methods: ^1.1.0
  http_parser: ^4.0.2
  mailer: 
  meta: ^1.9.0
  mime: ^1.0.4
  shelf: ^1.4.1
  shelf_cors_headers: 
  shelf_hotreload: ^1.3.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

  postgres: any
dev_dependencies:
  build_runner:
  lints: ^3.0.0
  mocktail: ^1.0.0
  shelf_router_generator:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
  