openapi: '3.0.0'
info:
  version: '0.0.1'
  title: 'Bita Markets'
  description: Inventory and Markets
  license: 
    name: MIT
    url: https://bita.gumiapps.com/license
    
servers:
  - url: http://127.0.0.1:8000
  - url: https://bita.gumiapps.com
paths:
  #############################User#####################################
  /auth/get_started_with_phone:
    $ref: "accounts/auth.yaml#/paths/~1auth~1get_started_with_phone"
  /auth/get_started_with_email:
    $ref: "accounts/auth.yaml#/paths/~1auth~1get_started_with_email"
  /auth/verify_otp:
    $ref: "accounts/auth.yaml#/paths/~1auth~1verify_otp"
  /auth/login:
    $ref: "accounts/auth.yaml#/paths/~1auth~1login"
  /auth/change_phone:
    $ref: accounts/auth.yaml#/paths/~1auth~1change_phone
  /auth/verify_change_phone/{requestId}/{token}:
    $ref: accounts/auth.yaml#/paths/~1auth~1verify_change_phone~1{requestId}~1{token}
  /auth/change_email:
    $ref: accounts/auth.yaml#/paths/~1auth~1change_email
  /auth/verify_change_email/{requestId}/{token}:
    $ref: accounts/auth.yaml#/paths/~1auth~1verify_change_email~1{requestId}~1{token}
  /auth/change_password:
    $ref: accounts/auth.yaml#/paths/~1auth~1change_password
  /auth/set_password:
    $ref: accounts/auth.yaml#/paths/~1auth~1set_password
  /auth/me:
    $ref: "accounts/auth.yaml#/paths/~1me"

  /users/{id}:
    $ref: "accounts/user.yaml#/paths/~1{id}"
  # Shopping
  /shopping/items:
    $ref: "shopping/shopping.yaml#/paths/~1items"
  #####################################################################
  /shopping/bussiness/popular:
    $ref: "shopping/shopping.yaml#/paths/~1businesses~1popular"
  /shopping/bussiness/suggested:
    $ref: "shopping/shopping.yaml#/paths/~1businesses~1suggested"
  /shopping/products/popular:
    $ref: "shopping/shopping.yaml#/paths/~1products~1popular"
  /shopping/products/suggested:
    $ref: "shopping/shopping.yaml#/paths/~1products~1suggested"
  /shopping/products/{bizId}:
    $ref: "shopping/shopping.yaml#/paths/~1products~1{bizId}"
  #####################################################################
  /business/catagories:
    $ref: "business/business.yaml#/paths/~1catagories"
  /business/brands:
    $ref: "business/business.yaml#/paths/~1brands"
  ##############################Businness##############################
  /business:
    $ref: "business/business.yaml#/paths/~1business"
  /business/{id}:
    $ref: "business/business.yaml#/paths/~1business~1{id}"
  /business/mine:
    $ref: "business/business.yaml#/paths/~1business~1me"
  #############################Business Preference#####################
  /business/bussiness/settings/{id}:
    $ref: "business/business.yaml#/paths/~1settings~1{id}"
  /business/bussiness/contacts/{id}:
    $ref: "business/business.yaml#/paths/~1business~1contacts~1{id}"
  /business/bussiness/address/{id}:
    $ref: "business/business.yaml#/paths/~1business~1addresses~1{id}"
  #############################Product#################################
  /business/products:
    $ref: "business/business.yaml#/paths/~1products"
  /business/products/{bizId}:
    $ref: "business/business.yaml#/paths/~1products~1{bizId}"
  /business/products/{bizId}/{productId}:
    $ref: "business/business.yaml#/paths/~1products~1{bizId}~1{productId}"

  
components:
  securitySchemes:
      $ref: components.yaml#/components/securitySchemes
   

security:
  - ApiKey: []