openapi: '3.0.0'
info:
  version: '0.0.1'
  title: 'Bita Markets'
  description: Inventory and Markets
  license: 
    name: MIT
    url: https://bita.gumiapps.com/license
    
servers:
  - url: http://127.0.0.1:8000
  - url: https://bita.gumiapps.com
paths:
  # Paths related to users
  /users/getStartedWithPhone:
    $ref: "user/user.yaml#/paths/~1users~1getStartedWithPhone"
  /users/getStartedWithEmail:
    $ref: "user/user.yaml#/paths/~1users~1getStartedWithEmail"
  /users/verifyOtp:
    $ref: "user/user.yaml#/paths/~1users~1verifyOtp"
  /users/login:
    $ref: "user/user.yaml#/paths/~1users~1login"

  /users/{id}:
    $ref: "user/user.yaml#/paths/~1{id}"
  /users/me:
    $ref: "user/user.yaml#/paths/~1me"
  # Shopping
  /shopping/items:
    $ref: "shopping/shopping.yaml#/paths/~1items"
  # /shopping/bussiness/{id}:
    # $ref: "shopping/shopping.yaml#/paths/~1business~1{id}"
  /shopping/bussiness/popular:
    $ref: "shopping/shopping.yaml#/paths/~1businesses~1popular"
  /shopping/bussiness/suggested:
    $ref: "shopping/shopping.yaml#/paths/~1businesses~1suggested"
  /shopping/products/popular:
    $ref: "shopping/shopping.yaml#/paths/~1products~1popular"
  /shopping/products/suggested:
    $ref: "shopping/shopping.yaml#/paths/~1products~1suggested"
  /shopping/products/{bizId}:
    $ref: "shopping/shopping.yaml#/paths/~1products~1{bizId}"
  # /shopping/catagories:  
  #   $ref: "shopping/shopping.yaml#/paths/~1businesses~1catagories"
  # /shopping/brands:
  #   $ref: "shopping/shopping.yaml#/paths/~1businesses~1brands"
    # inventory 
  /inventory/catagories:
    $ref: "business/business.yaml#/paths/~1catagories"
  /business/brands:
    $ref: "business/business.yaml#/paths/~1brands"
  # Businness
  /business:
    $ref: "business/business.yaml#/paths/~1business"
  /business/{id}:
    $ref: "business/business.yaml#/paths/~1business~1{id}"
  /business/mine:
    $ref: "business/business.yaml#/paths/~1business~1me"
  # Business Preference
  /business/bussiness/settings/{id}:
    $ref: "business/business.yaml#/paths/~1settings~1{id}"
  # Product
  /business/products:
    $ref: "business/business.yaml#/paths/~1products"
  /business/products/{bizId}:
    $ref: "business/business.yaml#/paths/~1products~1{bizId}"
  /business/products/{bizId}/{productId}:
    $ref: "business/business.yaml#/paths/~1products~1{bizId}~1{productId}"

  
components:
  securitySchemes:
      $ref: components.yaml#/components/securitySchemes
   

security:
  - ApiKey: []