openapi: '3.0.0'
info:
  version: '0.0.1'
  title: 'Bita Markets'
  description: Inventory and Markets
  license: 
    name: MIT
    url: https://bita.gumiapps.com/license
    
servers:
  - url: http://127.0.0.1:8000
  - url: https://bita.gumiapps.com
paths:
  # Paths related to users
  /users/account/getStartedWithPhone:
    $ref: "user/user.yaml#/paths/~1users~1getStartedWithPhone"
  /users/account/getStartedWithEmail:
    $ref: "user/user.yaml#/paths/~1users~1getStartedWithEmail"
  /users/account/verifyOtp:
    $ref: "user/user.yaml#/paths/~1users~1verifyOtp"

  /users/{id}:
    $ref: "user/user.yaml#/paths/~1{id}"
  # Shopping
  /shopping/items:
    $ref: "shopping/product.yaml#/paths/~1items"
  /shopping/shops/{id}:
    $ref: "shopping/product.yaml#/paths/~1shops~1{id}"
  /shopping/shops/popular:
    $ref: "shopping/product.yaml#/paths/~1shops~1popular"
  /shopping/catagories:  
    $ref: "shopping/product.yaml#/paths/~1shops~1catagories"
  /shopping/brands:
    $ref: "shopping/product.yaml#/paths/~1shops~1brands"
    # inventory 
  /inventory/brands:
    $ref: "stock/stock.yaml#/paths/~1brands"
  /inventory/catagories:
    $ref: "stock/stock.yaml#/paths/~1catagories"
  /inventory/shops:
    $ref: "stock/stock.yaml#/paths/~1shops"
  /inventory/shops/me:
    $ref: "stock/stock.yaml#/paths/~1shops~1me"
  /inventory/shops/{id}:
    $ref: "stock/stock.yaml#/paths/~1shops~1{id}"
  /inventory/shops/settings/{id}:
    $ref: "stock/stock.yaml#/paths/~1settings~1{id}"
  # /inventory/products:
  #   $ref: "stock/stock.yaml#/paths/~1products"
  /inventory/products/{id}:
    $ref: "stock/stock.yaml#/paths/~1products~1{id}"

  



  
components:
  securitySchemes:
      $ref: components.yaml#/components/securitySchemes
   

security:
  - ApiKey: []
  - BearerToken: []
  - basicHttpAuthentication: []