paths:
  # filters: price, distance
  /items:
    get:
      operationId: getItems
      summary: Get Items
      tags: 
        - Shopping🛒
      security:
        - ApiKey: []
      responses:
        200:
          description: Request Successfully completed
          content:
            application/json:
              schema:
                type: array
                required:
                  - product
                items:
                    $ref: "../components.yaml#/components/schemas/ProductView"
              example:
                - id: 10
                  name: Samsung s10 plus
                  price: 27000
                  shopId: 12

        403:
          $ref: "../error_responses.yaml#/responses/403"
  /shops/{id}:
    get:
      parameters:
        - name: id
          in: path
          schema: 
            $ref: ../components.yaml#/components/schemas/Id
      operationId: GetShopById
      summary:  Get shop by id
      tags: 
        - Shopping🛒
      security:
        - ApiKey: []
      responses:
        200:
          description: Provide Id to get shop
          content:
            application/json:
              schema:
                type: array
        403:
          $ref: "../error_responses.yaml#/responses/403"
  /shops/popular:
    get:
      operationId: GetPopularShop
      summary:  Get Popular Shops
      tags: 
        - Shopping🛒
      security:
        - ApiKey: []
      responses:
        200:
          description: Provide Id to get shop
          content:
            application/json:
              schema:
                type: array
                items:
                    type: object
        403:
          $ref: "../error_responses.yaml#/responses/403"
  /shops/catagories:
    get:
      operationId: GetCatagories
      summary:  Get shop Catagories
      tags: 
        - Shopping🛒
      security:
        - ApiKey: []
      responses:
        200:
          description: Provide Id to get shop
          content:
            application/json:
              schema:
                type: array
                items:
                    type: object
        403:
          $ref: "../error_responses.yaml#/responses/403"
  /shops/brands:
    get:
      operationId: GetBrands
      summary:  Get shop Brands
      tags: 
        - Shopping🛒
      security:
        - ApiKey: []
      responses:
        200:
          description: Provide Id to get shop
          content:
            application/json:
              schema:
                type: array
                items:
                    type: object
        403:
          $ref: "../error_responses.yaml#/responses/403"

          
  /business/{id}:
    get:
      parameters:
        - name: id
          required: true
          in: path
          schema:
            $ref: "../components.yaml#/components/schemas/Id"
      operationId: GetShopsByIdInventory
      description: Get business for inventory
      summary: Get business for inventory
      tags: 
        - Stock
      responses:
        200:
          description: Request completed Successfully
          content:
            application/json:
              schema:
                $ref: "../components.yaml#/components/schemas/Bussiness"
         
        403:
          $ref: "../error_responses.yaml#/responses/403" 
        404:
          $ref: "../error_responses.yaml#/responses/404"
        500:
          $ref: "../error_responses.yaml#/responses/500" 
    