- name: CI for Bita Markets
  hosts: myhosts
  tasks:
    - name: Add Google Linux GPG public key
      become: true
      ansible.builtin.apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        keyring: /usr/share/keyrings/dart.gpg
    - name: Add the Dart package repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main

    - name: Update packages
      become: true
      ansible.builtin.apt:
        upgrade: yes

    - name: Install Dart
      become: true
      ansible.builtin.apt:
        name:
          - dart

    - name: Getting code base
      ansible.builtin.git:
        accept_hostkey: true
        clone: yes
        update: yes
        name: git@github.com:gumi-apps/bita_markets.git
        dest: bita_markets
    - name: Build Executable
      shell: cd bita_markets && dart pub get && dart compile exe bin/bita_markets.dart
    - name: Copy Environmental Variables
      ansible.builtin.copy:
        dest: /var/bita_markets_build
        force: true
        src: ~/bita_markets/.env
    - name: Copy Build
      become: true
      ansible.builtin.shell:
        name: cp bin/bita_markets.exe /var/bita_markets_build/bita_markets.exe
